- name: Run a play using the collections keyword
  hosts: all
  collections:
    - devsec.hardening
  roles:
    - name: Import a role
      ansible.builtin.import_role:
        name: devsec.hardening.os_hardening

